title: COVID-19 Projections
description: Based on the JHU & NYT Data
google_analytics: UA-2749983-3
theme: jekyll-theme-primer

kramdown:
    math_engine: mathjax

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README
  - LICENSE
  - README.md
  - LICENSE.md
