# Normally we would lock the versions down more,
# but nothing here is strongly version-dependent,
# so just lock the major version numbers for now.

name: covid19

channels:
  - defaults

dependencies:
  - black
  - cython
  - ipython
  - jinja2
  - jupyter
  - lxml
  - matplotlib=3.2.2
  - numpy=1.18
  - pandas=1.0.5
  - pep8
  - pip
  - pylint
  - python=3.8
  - ruamel_yaml
  - scikit-learn=0.22
  - scipy=1.4
  - seaborn=0.10
  - statsmodels=0.11
