title: COVID-19 Projections
description: Simple COVID-19 Projections based on the JHU CSSE Data
google_analytics: UA-2749983-3
theme: jekyll-theme-primer

kramdown:
    math_engine: mathjax

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
